openapi: 3.0.1
info:
  title: Create Fund Transfer Records Web Service API
  description: This is the API for creating Fund Transfer Records Web Service
  contact:
    name: Openbravo
    url: https://www.openbravo.com
  version: 1.0.0

servers:
  - url: ${contextURL}

paths:
  /ws/org.openbravo.advpaymentmngt.CreateFundTransferRecord:
    post:
      tags:
        -  Create Fund Transfer Record Web Service
      summary: Create Fund Transfer Record in Openbravo
      description: The Create Fund Transfer Record api provides a webservice to create the fund transfer records and its corresponding transactions
      operationId: create fund transfer record
      security:
        - ${AuthenticationName}: []
      requestBody:
        description: The fund transfer record will be created with defined accounts and amount
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
            examples:
              request1:
                value: {
                  "accountFrom": "Bank Account 1 - White Valley Spain",
                  "accountTo": "Cashbook 2 - Posest Store",
                  "glItem": "CTS Cash Differences",
                  "amount": "100",
                }
                summary: Create a Fund Transfer Record.
                description: Gives an example of creating a Fund Transfer Record with a minimal json.
              request2:
                value: {
                  "date": "2024-05-25",
                  "accountFrom": "Bank Account 1 - White Valley Spain",
                  "accountTo": "Cashbook 2 - Posest Store",
                  "glItem": "CTS Cash Differences",
                  "amount": "100",
                  "description": "fund transfer description"
                }
                summary: Create a Fund Transfer Record specifying the date and the description.
                description: Gives an example of creating a Fund Transfer Record with specific date and description.
      responses:
        200:
          description: Shows the created Fund Transfer Record values
          content:
            application/json:
              examples:
                result1:
                  value:
                    "data": {
                      "id": "15064868814340E38E7112EC77630E79",
                      "client": "The White Valley Group",
                      "organization": "White Valley Spain S.A",
                      "organization_info": {
                        "id": "BF129721D9FB4EB0819509934153E972",
                        "name": "White Valley Spain S.A",
                        "searchKey": "White Valley Spain S.A",
                        "taxID": "B87654321",
                        "organization_location": {
                          "address1": "Pau Claris 138 1-1",
                          "postalCode": "08009",
                          "city": "Barcelona",
                          "region": "BARCELONA  ",
                          "countryCode": "ES"
                        }
                      },
                      "date": "2024-10-21",
                      "documentNo": "1000001",
                      "creationDate": "2024-10-21 10:14:37",
                      "updated": "2024-10-21 10:14:37",
                      "createdBy": "Openbravo",
                      "updatedBy": "Openbravo",
                      "amount": 100,
                      "status": "CO",
                      "sourceTransaction": {
                        "id": "6965DA031CD64665850A48084614AFAE",
                        "client": "The White Valley Group",
                        "organization": "White Valley Spain S.A",
                        "organization_info": {
                          "name": "White Valley Spain S.A",
                          "searchKey": "White Valley Spain S.A",
                          "id": "BF129721D9FB4EB0819509934153E972"
                        },
                        "financialAccount": {
                          "name": "Bank Account 1 - White Valley Spain",
                          "currency": "EUR",
                          "type": "B"
                        },
                        "transactionType": "BPW",
                        "transactionDate": "2024-10-21",
                        "description": "Funds Transfer Transaction",
                        "depositAmount": 0,
                        "withdrawalAmount": 100
                      },
                      "destinationTransaction": {
                        "id": "948DA69733AB461987D9267EFF5D26FC",
                        "client": "The White Valley Group",
                        "organization": "Posets Store",
                        "organization_info": {
                          "name": "Posets Store",
                          "searchKey": "Posets Store",
                          "id": "B5DE96143D6642228E3B9DEC69886A47"
                        },
                        "financialAccount": {
                          "name": "Cashbook 2 - Posest Store",
                          "currency": "USD",
                          "type": "C"
                        },
                        "transactionType": "BPD",
                        "transactionDate": "2024-10-21",
                        "description": "Funds Transfer Transaction",
                        "depositAmount": 131.42,
                        "withdrawalAmount": 0
                      }
                    }
                    "links": null
                  summary: Shows the Fund Transfer Record has been successfully created
                  description: Shows the Fund Transfer Record has been successfully created
        401:
          $ref: '#/components/responses/UnauthorizedError'
        500:
          description: Error Response
          content:
            application/json:
              examples:
                error1:
                  value:
                    status: 500
                    title: "Error creating the Fund Transfer Record"
                    detail: Error while creating the Fund Transfer Record
components:
  schemas:
    Request:
      type: object
      properties:
        date:
          type: string
          format: YYYY-MM-DD
        accountFrom:
          type: string
        accountTo:
          type: string
        glItem:
          type: string
        amount:
          type: string
        description:
          type: string

      required:
        - accountFrom
        - accountTo
        - glItem
        - amount
      description: Input for Create Fund Transfer Record transaction WS.
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
  securitySchemes:
    ${AuthenticationName}:
      type: http
      scheme: ${AuthScheme}
      bearerFormat: ${AuthFormat}